---
title: "Morfología visual"
author: "Ricardo Michel MALLQUI BAÑOS"
institute: "Universidad Nacional San Cristóbal De Huamanga"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: krantz
link-citations: yes
subparagraph: yes
colorlinks: yes
fontsize: 16pt
bibliography: [book.bib, packages.bib]
biblio-style: apalike
lot: yes
lof: yes
monofont: "Source Code Pro"
monofontoptions: "Scale=0.7"
toc_appendix: yes
description: ""
---

```{=tex}
\newcommand{\N}{\mathbb{N}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\CC}{\mathbb{C}}
\newcommand{\I}{\mathbb{I}}
\newcommand{\f}{\mathbb{f}}
\newcommand{\X}{\mathbb{X}}
\newcommand{\D}{\mathbb{D}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\Q}{\mathbb{Q}}
\newcommand{\norm}[1]{\left\Vert#1\right\Vert}
\newcommand{\abs}[1]{\left\vert#1\right\vert}
\newcommand{\set}[1]{\left\{#1\right\}}
\newcommand{\seq}[1]{\left<#1\right>}
\newcommand{\co}[1]{\left[#1\right]}
\newcommand{\cc}[1]{\left(#1\right)}
\newcommand{\J}{\mathcal{J}}
\newcommand{\K}{\mathcal{K}}
\newcommand{\M}{\mathcal{M}}
\newcommand{\F}{\mathcal{F}}
```
# Resumen {.unnumbered}

La importancia del estudio de la forma en el arte plástico se debe a la manipulación constante de estas en el espacio bidimensional y tridimensional. En el plano bidimensional se estudian aspectos geometricos partiendo desde la forma de un punto hasta formas orgánicas con comportamientos similares al de los conjuntos fractales de Mandelbrot y Julia y en el espacio tridimensional se realiza un estudio sobre formas que viven en este espacio es decir tanto las formas bidimensionales además de los sólidos geométricos y las formas orgánicas y los conjuntos fractales de Mandelbrots 3D y julia 3D. Finalmente se realiza composiciones con estas formas, utilizando principios de composicon plástica con el objetivo de reunir los conocimientos previos y reconocer la utilidad de su estudio previo. Luego se reconocerán estas formas como contenedores de formas existentes en la naturaleza tales como las formas estudiadas en la fitomorfología, la zoomorfología, la geomorfologia. En el Apendice se describen conceptos relacionados a transformaciones y centros de masa de formas 2d y 3d.

# Introducción {.unnumbered}

El estudio de la forma de manera aislada o compositiva, en el arte plástico es de importancia para la manipulación correcta de estas, generando representación lógica; es decir desprovista de la intuición, la intuición, generalmente distorsiona el aspecto verdadero de las formas.

El espacio bidimensional se denota con el símbolo $\mathbb{R}^2$ y al espacio tridimensional se denota con el símbolo $\mathbb{R}^3$. Las formas bidimensionales pueden existir tanto el el espacio bidimensional y tridimensional y Las formas tridimensionales únicamente pueden se representados en el espacio tridimensional.

Las formas que reunen todas las caracteristicas de las formas bidimnesionales y tridmensionales son los las formas llamadas fractales tridimensionales que se generan bajo procesos de iteración o recursividad de transformaciones de las copias de ciertas formas básicas llamadas módulos, exiten modelos secuenciales que indican la recursividad, la formas concernientes a los fractales generadas por los números complejos son las llamadas conjuntos de Mandelbrot y Julia en el espacio bidimensional y el el espacio tridmencional se llaman conjuntos de Mandelbrot 3D y Julia 3D, estas formas manifiestan una variedad infinita.

El libro se realiza bajo las teorias y conceptos de diversas áreas tales como la botánica la geometría descriptiva, modelos matemáticos, que proveen de conceptos y objetos utilizados hasta el momento de manera intuitiva en las artes plásticas es decir se interrelaciona estos conocimientos con el objetivo de agruparlos de manera lógica y secuencial, avalada evidentemente por las teorías y la intuición genuina.

Las formas orgánicas son aquellas que escapan a una geometría especifica ya estudiadas pero pueden ser estudiadas bajo criterios de geometrización es decir generando una red geométrica que lo inscriban, esto es identificando los puntos sobre la forma que sirvan de anclaje o vertice, estos puntos pueden pertenecer o no la forma en el primer caso se debe considerar que sean puntos más resaltantes de la forma, en el sugundo caso deben ser punto de manera que generan segmentos tangentes a la forma considerada.

El libro se compone de cinco capítulos en los cuales se describen los temas de manera secuencial además de dos apéndices que sirven como reforzamiento de la ideas vertidas en el texto es decir en el primer capitulo se describe la teoría de la forma en el espacio bidimensional, en el capitulo 2 se describe la teoría de las formas tridimensionales, en el tercer capítulo concierne a la teoría de formas compositivas, el capítulo 4 formas orgánicas y su geometría, el capítulo 5 formas abstractas y su geometría.


